version: '2.1'

services:
    client:
        image: dev-client
        build: ./client
        environment:
            NODE_ENV: dev
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app

    api:
        image: dev-server
        build: ./server
        environment:
            NODE_ENV: dev
            HTTP_PORT: 8080
        volumes:
            - ./server:/usr/src/app
        depends_on:
            - redis
            - mysql

    redis:
        image: redis:5
        ports:
            - 63799:6379
        command: redis-server --appendonly yes
        volumes:
            - .redis-db:/data

    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api

    mysql:
        image: mysql:5
        ports:
            - 33066:3306
        volumes:
            - .db:/var/lib/mysql
        environment:
            MYSQL_USER: chat
            MYSQL_PASSWORD: chat
            MYSQL_DATABASE: chat
            MYSQL_ROOT_PASSWORD: 123321
