version: '2.1'

services:
    client:
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app

    api:
        build: ./server
        volumes:
            - ./server:/usr/src/app
        depends_on:
            - redis
            - mysql
            - db_migrator
        env_file: server/.env
        command: 'scripts/wait-for-it.sh mysql:3306 -- npm start'

    db_migrator:
        build: ./server
        volumes:
            - ./server:/usr/src/app
        command: ./scripts/wait-for-it.sh mysql:3306 -- npx knex migrate:latest
        depends_on:
            - mysql
        env_file: server/.env

    redis:
        image: redis:5
        ports:
            - 63799:6379
        command: redis-server --appendonly yes
        volumes:
            - .redis-db:/data
        env_file: server/.env

    nginx:
        image: nginx:latest
        ports:
            - '8000:8000'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api

    mysql:
        image: mysql:5
        ports:
            - 33066:3306
        volumes:
            - .db:/var/lib/mysql
        env_file: server/.env
